### ISSUE TITLE
CSS基础测试12 - 徽章

### ISSUE THREAD

**Issue by JaimeCheng** [JaimeCheng/zxx-quiz-summary#12]
**题目：**
![css12](https://user-images.githubusercontent.com/22406024/65161926-044cab00-da6b-11e9-94b0-f4df26afd276.png)

[原issue](https://github.com/zhangxinxu/quiz/issues/44)

**回答：**
```css
/* 我的回答 */
.cover {
  position: relative;
  display: inline-block;
}
.cover img {
  width: 120px;
  height: 160px;
}
.tag {
  color: #fff;
  font-size: 12px;
  position: absolute;
}
.tag1 {
  padding: 4px 6px;
  top: 0;
  left: 0;
  line-height: 1;
  background: #cd0000;
}
.tag2 {
  z-index: 0;
  padding: 1px 5px;
}
.tag2::after {
  content: '';
  position: absolute;
  z-index: -1;
  top: 0;
  left: -0;
  border: 15px solid transparent;
  border-top: 15px solid #cd0000;
  border-left: 15px solid #cd0000;
}
.tag3 {
  padding: 0 6px;
  line-height: 22px;
  z-index: 0;
}
.tag3::after {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  z-index: -1;
  width: 100%;
  height: 0;
  border-width: 0px 8px 22px 0px;
  border-style: none solid solid;
  border-color: transparent transparent #cd0000;
  transform: scale(1, -1)
}
.tag4 {
  width: 25px;
  height: 25px;
  line-height: 22px;
  padding: 0px 6px;
  background: #cd0000;
  border-radius: 0px 0px 25px 0px;
  box-sizing: border-box;
}
.tag5 {
  width: fit-content;
  height: 25px;
  line-height: 20px;
  padding: 0px 10px 0 6px;
  background: #cd0000;
  border-radius: 0 0 100% 0;
  box-sizing: border-box;
}
```
[满分回答1](https://github.com/zhangxinxu/quiz/issues/44#issuecomment-533057373) | [满分回答2](https://github.com/zhangxinxu/quiz/issues/44#issuecomment-532733360) | [满分回答3](https://github.com/zhangxinxu/quiz/issues/44#issuecomment-533179960) | [满分回答4](https://github.com/zhangxinxu/quiz/issues/44#issuecomment-532746701)

**总结：**
1. css实现各种图标图形有一直不太擅长；
2. 第三题的图形不能自适应文字高度等； 
3. 第4题没弄清题意，两个应该是一道题，根据内容长度自动变椭圆；
4. 自己实现出来的方法不够简单；

[> 在线demo <](https://codepen.io/JaimeCheng/pen/NWKOaMw?editors=1100)
