### ISSUE TITLE
CSS基础测试13 - GitHub徽章

### ISSUE THREAD

**Issue by JaimeCheng** [JaimeCheng/zxx-quiz-summary#15]
**题目：**
![css13](https://user-images.githubusercontent.com/22406024/67081409-a9bd8080-f1c9-11e9-8892-bd146a00d814.png)

[原issue](https://github.com/zhangxinxu/quiz/issues/47)

**回答：**
```html
<!-- 我的回答 8分 -->
<form class="social-form">
  <details class="select-menu">
    <summary class="select-menu-button btn"aria-haspopup="menu" role="button"> 
      <span>
        <svg viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">
          <path fill-rule="evenodd"
            d="M8.06 2C3 2 0 8 0 8s3 6 8.06 6C13 14 16 8 16 8s-3-6-7.94-6zM8 12c-2.2 0-4-1.78-4-4 0-2.2 1.8-4 4-4 2.22 0 4 1.8 4 4 0 2.22-1.78 4-4 4zm2-4c0 1.11-.89 2-2 2-1.11 0-2-.89-2-2 0-1.11.89-2 2-2 1.11 0 2 .89 2 2z">
          </path>
        </svg>
        Unwatch
      </span>
    </summary>
  </details>
  <a class="social-count" href="#">64</a>
</form>
<form class="social-form">
  <button type="submit" class="btn btn-with-count"> 
    <svg viewBox="0 0 14 16" version="1.1" width="14" height="16"
      aria-hidden="true">
      <path fill-rule="evenodd" d="M14 6l-4.9-.64L7 1 4.9 5.36 0 6l3.6 3.26L2.67 14 7 11.67 11.33 14l-.93-4.74L14 6z">
      </path>
    </svg>
    Star
  </button>
  <a class="social-count" href="#">445</a>
</form>
<form class="social-form">
  <button type="submit" class="btn btn-with-count">
    <svg viewBox="0 0 10 16" version="1.1" width="10" height="16" aria-hidden="true">
      <path fill-rule="evenodd"
        d="M8 1a1.993 1.993 0 00-1 3.72V6L5 8 3 6V4.72A1.993 1.993 0 002 1a1.993 1.993 0 00-1 3.72V6.5l3 3v1.78A1.993 1.993 0 005 15a1.993 1.993 0 001-3.72V9.5l3-3V4.72A1.993 1.993 0 008 1zM2 4.2C1.34 4.2.8 3.65.8 3c0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2zm3 10c-.66 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2zm3-10c-.66 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2z">
      </path>
    </svg>
    Fork
  </button>
  <a class="social-count" href="#">25</a>
</form>
```
```css
* {
  font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji;
}
[role=button]:focus, button { outline: none; box-shadow: none; }
summary::-webkit-details-marker { display:none; }
svg { display: inline-block; vertical-align: text-bottom; fill: currentColor; }
.select-menu { cursor: pointer; }
.btn {
  float: left;
  padding: 3px 10px;
  font-size: 12px;
  font-weight: 600;
  line-height: 20px;
  border-radius: 3px 0 0 3px;
  color: #24292e;
  background-image: linear-gradient(-180deg,#fafbfc,#eff3f6 90%);
  border: 1px solid rgba(27,31,35,.2);
}
.select-menu-button:after {
  display: inline-block;
  width: 0;
  height: 0;
  vertical-align: -2px;
  content: "";
  border: 4px solid transparent;
  border-top-color: currentcolor;
}
.social-count {
  float: left;
  padding: 3px 10px;
  font-size: 12px;
  font-weight: 600;
  line-height: 20px;
  color: #24292e;
  border: 1px solid rgba(27,31,35,.2);
  border-left: 0;
  border-radius: 0 3px 3px 0;
  text-decoration: none;
  margin-right: 10px;
}
```
[]() | []()

**总结：**
1. 还是多次强调的语义化；
2. 按钮组不允许换行；
3. 收获最大的是：使用树结构伪类，不要使用标签或类选择器；
4. table布局，天然一行显示，兼容到IE8。

[> 在线demo <](https://codepen.io/JaimeCheng/pen/ExxNrwr?editors=1100)
