### ISSUE TITLE
CSS基础测试14 - 面包屑

### ISSUE THREAD

**Issue by JaimeCheng** [JaimeCheng/zxx-quiz-summary#18]
**题目：**
![css14](https://user-images.githubusercontent.com/22406024/68456363-8621af00-0238-11ea-881a-00c0e06a7ae6.png)

[原issue](https://github.com/zhangxinxu/quiz/issues/50)

**回答：**
```css
/* 得分 8 */
.step-item {
  height: 40px;
  font-size: 14px;
  padding: 10px 25px;
  margin: 0 0 5px -15px;
  display: inline-block;
  box-sizing: border-box;
  text-decoration: none;
  color: #009fe9;
  background: #edf9ff;
  -webkit-clip-path: polygon(87% 0, 100% 50%, 87% 100%, 0 100%, 13% 50%, 0 0);
          clip-path: polygon(87% 0, 100% 50%, 87% 100%, 0 100%, 13% 50%, 0 0);
}
.step-item:first-of-type {
  color: #009fe9;
  -webkit-clip-path: polygon(0 0, 87% 0, 100% 50%, 87% 100%, 0% 100%);
          clip-path: polygon(0 0, 87% 0, 100% 50%, 87% 100%, 0% 100%);
}
.step-item.curr {
  color: #fff;
  background: #009fe9;
}
.step-item.step-curr~.step-item {
  color: #8c8c8c;
  background-color: #EBEDF0;
}
```
```html
<div class="step-bar">
  <a class="step-item">1-规则说明</a>
  <a class="step-item">2-参与活动</a>
  <a class="step-item curr">3-参与抽奖</a>
  <a class="step-item">4-奖品发放</a>
  <a class="step-item">5-查看结果</a>
</div>
```
[满分回答](https://github.com/zhangxinxu/quiz/issues/50#issuecomment-550375549) | [思路奇特回答](https://github.com/zhangxinxu/quiz/issues/50#issuecomment-550287444)

**总结：**
1. clip-path 不兼容 ie；
2. border必备；
3. transform: skew 厉害；
4. 导航最好不换行。

[> 在线demo <](https://codepen.io/JaimeCheng/pen/vYYjaEN?editors=1100)
