### ISSUE TITLE
CSS基础测试15 - 网格状布局

### ISSUE THREAD

**Issue by JaimeCheng** [JaimeCheng/zxx-quiz-summary#21]
**题目：**
![css15](https://user-images.githubusercontent.com/22406024/69776503-7d891c80-11d7-11ea-9787-d69b981b38d0.png)

[原issue](https://github.com/zhangxinxu/quiz/issues/53)

**回答：**
```css
/* 我的回答 7分 */
.grid-box {
  display: grid;
  width: fit-content;
  margin: 20px;
  background: #5f5750;
  list-style: none;
  grid-template-columns: repeat(3, minmax(120px, 1fr));
  overflow: hidden;
}
.grid-box a {
  color: #fff;
  font-size: 16px;
  padding: 20px 0;
  display: block;
  text-decoration: none;
}
.grid-box li {
  text-align: center;
  padding: 10px;
  position: relative;
}
.grid-box li:before {
  content: "";
  position: absolute;
  top: 10px;
  right: -1px;
  width: 1px;
  height: calc(100% - 20px);
  background-color: #9B9692;
}
.grid-box li:after {
  content: "";
  position: absolute;
  bottom: -1px;
  left: 10px;
  width: calc(100% - 20px);
  height: 1px;
  background-color: #9B9692;
}
```
```html
<ul class="grid-box">
  <li><a href=""><i class="iconfont"></i>选购手机</a></li>
  <li><a href=""><i class="iconfont"></i>企业团购</a></li>
  <li><a href=""><i class="iconfont"></i>一元活动</a></li>
  <li><a href=""><i class="iconfont"></i>限时秒杀</a></li>
  <li><a href=""><i class="iconfont"></i>以旧换新</a></li>
  <li><a href=""><i class="iconfont"></i>话费充值</a></li>
</ul>
```
优秀回答： [grid](https://github.com/zhangxinxu/quiz/issues/53#issuecomment-559094860) | [flex](https://github.com/zhangxinxu/quiz/issues/53#issuecomment-559357800) | [@media](https://github.com/zhangxinxu/quiz/issues/53#issuecomment-559480564) | [box-shadow](https://github.com/zhangxinxu/quiz/issues/53#issuecomment-559456519)

**总结：**
1. 考虑健壮性：不修改css的情况下html结构能按需自适应；
2. 线的绘制，多种方案，不要拘泥与border一种。

[> 在线demo <](https://codepen.io/JaimeCheng/pen/JjjgNaM?editors=1100)
