### ISSUE TITLE
CSS基础测试16 - 两栏自适应

### ISSUE THREAD

**Issue by JaimeCheng** [JaimeCheng/zxx-quiz-summary#24]
**题目：**

![css16](https://user-images.githubusercontent.com/22406024/71105951-5f707400-21f9-11ea-82e8-62cec4777d51.png)

[原issue](https://github.com/zhangxinxu/quiz/issues/57)

**回答：** 8分
**方法一**
```css
.quiz {
  display: table;
}
.quiz-h {
  vertical-align: middle;
  padding: 0 10px;
  margin: 0;
}
.quiz-p {
  text-align: justify;
  padding: 0 10px;
}
```
**方法二**
```css
.quiz {
  align-items: center;
}
.quiz-h {
  margin: 0 10px;
}
.quiz-p {
  flex: 1;
  text-align: justify;
  margin: 0 10px;
}
```
**方法三**
```css
.quiz {
  white-space: nowrap;
}
.quiz-h {
  margin: 0 10px;
}
.quiz-p {
  text-align: justify;
  white-space: normal;
  vertical-align: middle;
  margin: 0 96px 0 0;
}
```
**方法四**
```css
.quiz {
  padding-left: 71px;
  position: relative;
}
.quiz-h {
  left: 0;
  top: 0;
  bottom: 0;
  margin:auto 10px;
  height: 0;
  line-height: 0;
}
.quiz-p {
  text-align: justify;
  margin: 0 10px;
}
```
[优秀回答](https://github.com/zhangxinxu/quiz/issues/57#issuecomment-568957858) | [获赞回答](https://github.com/zhangxinxu/quiz/issues/57#issuecomment-567075754) | [高分回答](https://github.com/zhangxinxu/quiz/issues/57#issuecomment-567066390)

**总结：**
1. 没考虑到文字很少的情况；
2. inlinle-block实现，自己其实不是很会；
3. 方法很多要多向大家学习！

[> 代码补全测试 <](http://quiz.xiliz.com/css-quiz16.html)
