### ISSUE TITLE
CSS基础测试9 - 标题打点

### ISSUE THREAD

**Issue by JaimeCheng** [JaimeCheng/zxx-quiz-summary#3]
**题目：**
![css09](https://user-images.githubusercontent.com/22406024/61383825-01560280-a8e2-11e9-8a99-a1388fe517a5.png)
[原issue](https://github.com/zhangxinxu/quiz/issues/34)

**回答：**
```css
/* 我的回答 兼容ie10 8分 */
* {
  padding: 0;
  margin: 0;
}
@media screen and (min-width: 375px) {
  html {
    font-size: calc(100% + 2 * (100vw - 375px) / 39);
    font-size: calc(16px + 2 * (100vw - 375px) / 39);
  }
}
@media screen and (min-width: 414px) {
  html {
    font-size: calc(112.5% + 2 * (100vw - 414px) / 586);
    font-size: calc(18px + 2 * (100vw - 414px) / 586);
  }
}
ul, li {
  list-style: none;
}
.article {
  width: 100%;
  max-width: 800px;
  margin: auto;
}
.article-item {
  display: flex;
}
.article-item__title {
  color: #9A9EA4;
  font-size: 1rem;
  flex: 1;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  text-align: left;
}
.article-item__title.prefix {
  direction: rtl;
}
.article-item__tags {
  float: right;
  margin-left: 5px;
}
.article-item__tags span {
  padding: 0 3px;
  font-size: 0.73rem;
  border-radius: 2px;
}
.article-item__tags__category {
  color: #A5ABB1;
  border: 1px solid #A5ABB1;
}
.article-item__tags__status {
  color: #EE4E54;
  border: 1px solid #EE4E54;
}
.article-item__tags__count {
  color: #5391EF;
  border: 1px solid #5391EF;
}
```
```html
<div class="article">
  <ul class="article-list">
    <li class="article-item">
      <div class="article-item__title suffix">这次是一个新的故事。浩劫余生终见光明</div>
      <div class="article-item__tags">
        <span class="article-item__tags__category">都市</span>
        <span class="article-item__tags__status">连载中</span>
        <span class="article-item__tags__count">54.82万字</span>
      </div>
    </li>
    <li class="article-item">
      <div class="article-item__title suffix">穿越天地复苏的平行世界偶获诸天聊天群</div>
      <div class="article-item__tags">
        <span class="article-item__tags__category">都市</span>
        <span class="article-item__tags__status">完本</span>
        <span class="article-item__tags__count">1万字</span>
      </div>
    </li>
    <li class="article-item">
      <div class="article-item__title suffix">修真四万年</div>
      <div class="article-item__tags">
        <span class="article-item__tags__category">科幻</span>
        <span class="article-item__tags__status">完本</span>
        <span class="article-item__tags__count">1059.98万字</span>
      </div>
    </li>
  </ul>
  <ul class="article-list">
    <li class="article-item">
      <div class="article-item__title prefix">这次是一个新的故事。浩劫余生终见光明</div>
      <div class="article-item__tags">
        <span class="article-item__tags__category">都市</span>
        <span class="article-item__tags__status">连载中</span>
        <span class="article-item__tags__count">54.82万字</span>
      </div>
    </li>
    <li class="article-item">
      <div class="article-item__title prefix">穿越天地复苏的平行世界偶获诸天聊天群</div>
      <div class="article-item__tags">
        <span class="article-item__tags__category">都市</span>
        <span class="article-item__tags__status">完本</span>
        <span class="article-item__tags__count">1万字</span>
      </div>
    </li>
    <li class="article-item">
      <div class="article-item__title prefix">修真四万年</div>
      <div class="article-item__tags">
        <span class="article-item__tags__category">科幻</span>
        <span class="article-item__tags__status">完本</span>
        <span class="article-item__tags__count">1059.98万字</span>
      </div>
    </li>
  </ul>
</div>
```
[最高分回答](https://github.com/zhangxinxu/quiz/issues/34#issuecomment-512197863) 

**总结：**
1. css写的不够精简，可以使用标签自定义属性代替繁多的class；
2. float布局很久不用忘了，这些应该彻底掌握不能忘记；
3. ie8不兼容rem单位；
4. table布局需要专门学习和练习；
5. 尽可能地保持dom位置和视觉的一致；
6. `border-color`会继承字体的`color`，css基础不够扎实；

[> 在线demo <](https://codepen.io/JaimeCheng/pen/NQKYbQ?editors=1100)
