### ISSUE TITLE
CSS基础测试10 - 下拉导航

### ISSUE THREAD

**Issue by JaimeCheng** [JaimeCheng/zxx-quiz-summary#6]
**题目：**
![css10](https://user-images.githubusercontent.com/22406024/62679573-7bf8d600-b9e7-11e9-8ea5-c33131fe903b.png)

[原issue](https://github.com/zhangxinxu/quiz/issues/37)

**回答：**
```css
// 我的回答 7分
* { padding: 0; margin: 0; }
ul,li { list-style: none; }
.menu-list { width: 160px; height: 90vh; border: 1px solid #ccc; border-top: none; border-bottom: none; padding: 20px 0; }
.menu-sub { display: none;  transition: .2s;}
.menu-item-icon { display: inline-block; transform: rotate(90deg); transition: .2s; }
.menu-item { display: flex; justify-content: space-between; padding: 0 10px; line-height: 40px; }
.menu-group input { position: absolute; display: block; width: 100%; height: 40px; top: 0; opacity: 0; z-index: 0;}
.menu-group {position: relative; }
.menu-group input:checked+.menu-item .menu-item-icon{ transform: rotate(270deg); }
.menu-group input:checked+.menu-item+.menu-sub { display: block; }
.menu-sub-item {line-height: 40px; padding-left: 30px; font-size: 14px; cursor:default; }
.menu-sub-item:hover { background: #EDF9FF; color: #33b2ee; }
```
```html
<div class="menu-list">
  <div class="menu-group">
    <input type="checkbox">
    <div class="menu-item">
      <b>布局</b>
      <span class="menu-item-icon">></span>
    </div>
    <ul class="menu-sub">
      <li class="menu-sub-item">Flex布局</li>
      <li class="menu-sub-item">Grid布局</li>
      <li class="menu-sub-item">Shapes布局</li>
      <li class="menu-sub-item">Columns布局</li>
    </ul>
  </div>
  <div class="menu-group">
    <input type="checkbox">
    <div class="menu-item">
      <b>组件</b>
      <span class="menu-item-icon">></span>
    </div>
    <ul class="menu-sub">
      <li class="menu-sub-item">按钮</li>
      <li class="menu-sub-item">输入框</li>
      <li class="menu-sub-item">下拉列表</li>
      <li class="menu-sub-item">单复选框</li>
    </ul>
  </div>
</div>
```
[满分回答](https://github.com/zhangxinxu/quiz/issues/37#issuecomment-519077646)
**总结：**
1. 注意语义化；
2. h5新增标签不熟悉也不常去用，越不用越不熟；
3. 小图标偷了懒没有做，直接用的标点符号；

[> 在线demo <](https://codepen.io/JaimeCheng/pen/BXrpea?editors=1100)
